# Generated by Django 5.0.1 on 2024-01-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="name",
            field=models.CharField(default="old_site", max_length=50),
            preserve_default=False,
        ),
    ]
